{
    'name': 'HR Shift Allowance Balance',
    'summary': 'Simple shift allowance balance add, deduct, carry-forward, and monthly closing workflow.',
    'description': """
HR Shift Allowance Balance
==========================
Simple workflow to add shift allowance, deduct paid shift allowance, view employee balance, and close or carry forward monthly balances.
    """,
    'version': '17.0.1.9.0',
    'category': 'Human Resources/Employees',
    'author': 'Generated by OpenAI',
    'website': 'https://www.odoo.com',
    'license': 'LGPL-3',
    'depends': ['hr', 'hr_contract', 'mail', 'web', 'report_xlsx'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence.xml',
        'data/hr_compensation_days_sequence.xml',
        'views/hr_shift_allowance_views.xml',
        'views/hr_compensation_days_mission_type_views.xml',
        'views/hr_compensation_days_views.xml',
        'views/hr_compensation_days_batch_views.xml',
        'views/hr_employee_views.xml',
        'wizard/hr_shift_allowance_wizard_views.xml',
        'wizard/hr_compensation_days_close_wizard_views.xml',
        'report/shift_allowance_close_report.xml',
        'reports/close_shift_allowance_month_report.xml',
        'views/menu_views.xml',
        'views/hr_compensation_days_menu.xml',
        'data/hr_compensation_days_company_fix.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
